name = "backend"
main = "src/index.ts"
compatibility_date = "2024-12-21"

# compatibility_flags = [ "nodejs_compat" ]

 [vars]
DATABASE="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZTkxMjJhYWUtZDAxNy00MTNjLTk4NWItNTE5YTk3MDNmYjcxIiwidGVuYW50X2lkIjoiMmExMWNjYjI0ZGU0Yzg1NDM4YTQ0ZDYxNjk2MjVhZTE1MjBmNjBlNDAyYzJjMDNmNjc1MWIzOTE0YTM1ZTgwMCIsImludGVybmFsX3NlY3JldCI6IjcwZmVkNjFiLWI0ODktNDgwYy05MDBhLWU0YWU4OWMxODQ3MyJ9.mbcax4TNsJVzR2aKrt6pOTVaAqyhKXO637V1yTBeBo4"
JWT_SECRET = "abracadabra"
